export const environment = {
  production: true,
  originToken:
    'Av2zrJE1SXXWr9LaIOd5BD2dmKCHMBCKp2nQYR/L0M/oBULOtXVlhy7GJdijAXod6gkL2r9GdTQNyQTD5rO+AQAAAAB2eyJvcmlnaW4iOiJodHRwczovL2RldnBhcmFuYS5teDo0NDMiLCJmZWF0dXJlIjoiVW5yZXN0cmljdGVkU2hhcmVkQXJyYXlCdWZmZXIiLCJleHBpcnkiOjE2Mzk1MjYzOTksImlzU3ViZG9tYWluIjp0cnVlfQ==',
}
