import '@devpr/common-elements'
import '@devpr/web-buttons'
import '@devpr/web-avatars'
import '@devpr/web-icons'
import '@devpr/web-forms'

import './app/buttons'
import './app/avatars'
import './app/forms'
import './app'
